// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremiumCalculatorApp.Data;

namespace PremiumCalculatorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PremiumCalculatorApp.Models.Occupation", b =>
                {
                    b.Property<int>("OccupationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OccupationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("OccupationId");

                    b.ToTable("Occupation");

                    b.HasData(
                        new
                        {
                            OccupationId = 1,
                            OccupationName = "Cleaner",
                            RatingId = 3
                        },
                        new
                        {
                            OccupationId = 2,
                            OccupationName = "Doctor",
                            RatingId = 1
                        },
                        new
                        {
                            OccupationId = 3,
                            OccupationName = "Author",
                            RatingId = 2
                        },
                        new
                        {
                            OccupationId = 4,
                            OccupationName = "Farmer",
                            RatingId = 4
                        },
                        new
                        {
                            OccupationId = 5,
                            OccupationName = "Mechanic",
                            RatingId = 4
                        },
                        new
                        {
                            OccupationId = 6,
                            OccupationName = "Florist",
                            RatingId = 3
                        });
                });

            modelBuilder.Entity("PremiumCalculatorApp.Models.RatingFactor", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingId");

                    b.ToTable("RatingFactor");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Factor = 1.00m,
                            Rating = "Professional"
                        },
                        new
                        {
                            RatingId = 2,
                            Factor = 1.25m,
                            Rating = "White Collar"
                        },
                        new
                        {
                            RatingId = 3,
                            Factor = 1.50m,
                            Rating = "Light Manual"
                        },
                        new
                        {
                            RatingId = 4,
                            Factor = 1.75m,
                            Rating = "Heavy Manual"
                        });
                });

            modelBuilder.Entity("PremiumCalculatorApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeathSumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OccupationId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("OccupationId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PremiumCalculatorApp.Models.User", b =>
                {
                    b.HasOne("PremiumCalculatorApp.Models.Occupation", "Occupation")
                        .WithMany()
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
